name: MoMustafaMD
favicon: null
layout_spectrum: 0.4788934059906751
typography_spectrum: 0.6653659252915531
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ee0000'
    - '#864d9e'
    - '#005200'
    - '#06b3ba'
    - '#fff4a4'
  brandStrength: 0.5
  lightness: 0.6601850239094347
  saturation: 0.38302379730157554
  rhythmicContrast: 0.9415997776668519
purpose: []
